#!/usr/bin/env python3

# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective
# number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

from Bio.Seq import Seq
from Bio.Alphabet import generic_dna

raw = "AGAAGTCCTATAGATTGGATCCAATTAGCGTAGAAGTCTGTAAGCGAT \
       ACGACCCCCTTTAGTCGAGTGTCGCCTGAGGGCTTATGTTCTTCGGCG \
       CCCGTAGTGGTGCCAGTTGATTGTCAGCTCCTGACATGGCTACTTCTA \
       ATTGTCTTTTATTACGGGGGGGCCGAGCCTCAGTGTGCCCCCCCCTGT \
       ATTAGCGACAGATTTACCTCTTCGTTAGAAGGAACAACCGAGAGAAGG \
       CCAGGGTGATTAATGCAAGCGGAGCTGACTTGCATCTTTCCTATTAAT \
       AGTATTGACTCCCGTTCCAAAGCGCCGATTATCGGGCACATGTTGATT \
       CATAGGCAACTATGAAATTGAAAGTTATAATGACTGGAAAGGCGGGCA \
       AGACGGCACTCAAGGCACGGACAACGAGCCCGCGAAATCAACTATTGT \
       AGCCGCGATAAACTTAAATTGGAGTAGCGTGGCGTCCGGAATCCAAGA \
       CGGCATACGGGGGTAACAAATGCTAGAAAGATGGAACGCCCCTGAAGT \
       CCCAAGCAAAGGGCCAAATTAACGGTTCCTGCACTACTGCCCGGGGCA \
       GGTCACCTCCTTCTCCATACTCCAATACATGCTGCAGGTAGGCCGATA \
       CTTTACGTGCCCAACGATGACGTTGATTAACCAGCCGTCTCGCAGGGA \
       TACGGCATCGTGAGAGGTGGCCTAGCTGCACAGGCCCCAGTTCATGCT \
       TAAGGTACTCGGTATACAGGAGTGCTAGGCTTATTACTAGCAACCGCC \
       AGTTAACTAACAATATAGTAGCCCCAAGACGGTATTCGCGCCCCTGGT \
       TGCCTTGAGTGTGTATCCGTTCTGCCATGGCACGCTCATAGGGCGATA \
       TCGATACATAACTCACGCACTTAAGGCCACGGGCACGACATGACATAA \
       CACTCTAACCTCTCTTCAATGGCCTATTTCGGCAGCTGGGAAGATGGT \
       GAGATCGGTTTTCGGTGAATATGCCATCA"

s = Seq(raw.replace(" ", ""), generic_dna)

[s.count(x) for x in ["A", "C", "G", "T"]]
