#!/usr/bin/env python3

# Given: A DNA string s of length at most 1000 bp.
# Return: The reverse complement sc of s.

raw = "CCCGTCCATGGGAACTACACAATTAAGGGCTCGCGCAATGTCTGGGCCGCCCACGCCGGGGTTCTG \
       TGAGCCTACTCCGAAAGGGTTCACCCATTAGAATGCAGGGATAACTCTTGTCTGAGATCTCTCTGC \
       GGTAGTGAAGAAGGCATTGTAATTTGTCATGGCAGTCGTCTGTGACAAGAACAGTCTTCGCTCGAC \
       AGGGCGGTTCATCCATCGTCTCTGACCCTACGTCATCCTACGTGTAGTTAAGTATAGTCACCACCA \
       GTATTTGTAGTGGCCCGACCCATAATCATACCAACTTCAGCCCTCCACATACGATTTTCCCCAGGT \
       GAGACAATAGATACTCATAGCAATCAATCCATGACGCATCACCTACTCGTTCACCAGTTAGAAACC \
       TACGACCGGTGGACCGTAAATCCGGATTCGGTTCGCCAACCCATTCTACTGTTCTACTTTGTAGGG \
       CGGGCTGGAACCAGTGGATGAAGTCGTCCTCAAGAACCTAGAAGATAAACAGTCCTGATCTGTAAG \
       TCATCCCTCTGTCAGTTAGGAGGCCATCCGTTTCGCACTCTCACAGCCCTGTTAAGACGAAGCGGG \
       CCCGGAAGGGCTGTGCCATATGAGTGTGCATGTTTCGCATTTGCCCTCATTTGTTTGACTCGTCTC \
       TCACAGACGGACAAAACGCAAGCTTTGCGATTCACTATTGGAACCTCCAGTTGATGTAATTTAAAG \
       TGTATAACTTCTCTATGCTATAATTACCGTCGAGGACGTTCACTCTTTGATAGAATCCGGACCGGT \
       AAAATGGAGAAGTGTGGTTTCGAAGGGGACGTCATAAGATTTTGTGTCCACGAAGACTGCTAGACC \
       GTGGCTCTACGCCTACACGCGGTATAATTAGAGTGAATGTTATCGACAAACCAGTTCCCGTTAGGG \
       CCCCCAACGAATCGTGGCTCCGGAAGCATTCTCAGTGTGCC"

s = raw.replace(" ", "")

sub = str.maketrans("ATGC", "TACG")
print(s[::-1].translate(sub))
