#!/usr/bin/env python3

# Problem 03
# In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.
# The reverse complement of a DNA string s is the string sc formed by reversing the symbols
# of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA"
# is "TGAC").
# Given: A DNA string s of length at most 1000 bp.
# Return: The reverse complement sc of s.


raw = "CCCGTCCATGGGAACTACACAATTAAGGGCTCGCGCAATGTCTGGGCCGCCCACGCCGGGGTTCTG \
       TGAGCCTACTCCGAAAGGGTTCACCCATTAGAATGCAGGGATAACTCTTGTCTGAGATCTCTCTGC \
       GGTAGTGAAGAAGGCATTGTAATTTGTCATGGCAGTCGTCTGTGACAAGAACAGTCTTCGCTCGAC \
       AGGGCGGTTCATCCATCGTCTCTGACCCTACGTCATCCTACGTGTAGTTAAGTATAGTCACCACCA \
       GTATTTGTAGTGGCCCGACCCATAATCATACCAACTTCAGCCCTCCACATACGATTTTCCCCAGGT \
       GAGACAATAGATACTCATAGCAATCAATCCATGACGCATCACCTACTCGTTCACCAGTTAGAAACC \
       TACGACCGGTGGACCGTAAATCCGGATTCGGTTCGCCAACCCATTCTACTGTTCTACTTTGTAGGG \
       CGGGCTGGAACCAGTGGATGAAGTCGTCCTCAAGAACCTAGAAGATAAACAGTCCTGATCTGTAAG \
       TCATCCCTCTGTCAGTTAGGAGGCCATCCGTTTCGCACTCTCACAGCCCTGTTAAGACGAAGCGGG \
       CCCGGAAGGGCTGTGCCATATGAGTGTGCATGTTTCGCATTTGCCCTCATTTGTTTGACTCGTCTC \
       TCACAGACGGACAAAACGCAAGCTTTGCGATTCACTATTGGAACCTCCAGTTGATGTAATTTAAAG \
       TGTATAACTTCTCTATGCTATAATTACCGTCGAGGACGTTCACTCTTTGATAGAATCCGGACCGGT \
       AAAATGGAGAAGTGTGGTTTCGAAGGGGACGTCATAAGATTTTGTGTCCACGAAGACTGCTAGACC \
       GTGGCTCTACGCCTACACGCGGTATAATTAGAGTGAATGTTATCGACAAACCAGTTCCCGTTAGGG \
       CCCCCAACGAATCGTGGCTCCGGAAGCATTCTCAGTGTGCC"

s = raw.replace(" ", "")

sub = str.maketrans("ATGC", "TACG")
s[::-1].translate(sub)
