#!/usr/bin/env python3

# Given: A DNA string t having length at most 1000 nt.
# Return: The transcribed RNA string of t.

raw = "ACGAGCUGGAAGGGAGCGCCUCUCUAGUCGUGCUGUUUUUUAACCAAGAAGUUUCACG \
       ACUCCCCCUAGACGCGUCGGCUUUGCUGUUACUCUCCCAAAGCCUUCUCUGACCGAUA \
       CGUGGCCCGUGUACACCUCUUACGUAUUCCAGCCGGCUAGAAGAUCGUUUCAAUUUAC \
       UCAAAGUUUGCAGAGAGUUGGCUAUUCGUUUGGCCCCGCUUUGGAAUAUUCUCCCAAA \
       AAAAGCUGUUCCUCGACGCUACGUUCUCGUGUCAAGCACACUACGCGAACGCCACUGG \
       GUCCAACUCGCGCAGAUGCCACUUUAUGUAGUCCCACUAUAGUUGGACCCUGGCGAGU \
       GCGAGUUGCGCCUACUGAUAAACUGUUGCGGCAGAAUACAUAAAGCGUAGCCUUAGAG \
       GUACCCCGUAAGACCCGCUCUGUCAGCAGUUUCACAUUACGGCGCCUGAGCCAACAUU \
       UGCCGCAUCAGGGUCACGAUUGGUCAAUUUUAAUUCGCAAACAUCCUCGGCUAUGAAC \
       UGUUAUAAACAUGCAGUCGAGACAUGGACCUAUUUGCUCCUGGCGCCGUUCUUAGAGC \
       UGCCCUUUCCUACGCGCCAGAUAGCAACUAAGGAAAUAAAGGAAUCAAGUCCAAGAAG \
       CUAGAACCUGUGGCCAUUCCUGGACCCGACUCACUGUCAGGCUCUGUUCGGCGCGGAU \
       GUCCCACGAUAGCUACAAGUCCGAGCUUUCCAGUCGCGCUCAAGCUUUCCAAGAUGUG \
       UCCGCGAGGGUUCUUUUCGCUCGGUCCUGUGGAACUUUUAAAUUCCUGGCGUCCCUAU \
       ACGCCGAGUAUACGAUUUGUUUCCUCUCGCUAUUGUUACGGUGAUAAUUUAUCGCUUU \
       GCCAUACUAGGAGUGUUCCUAUGUUUGAGGUGACCAGGAUUUA"

s = raw.replace(" ", "")
print(s.replace("T", "U"))
