#!/usr/bin/env python3

# Given: Two DNA strings s and t (each of length at most 1 kbp).
# Return: All locations of t as a substring of s.


# FIXME: write a more elegant recursive solution!
def get_matches(s, r):
    """Returns the 1-based index of substring r in s."""
    matches = []
    lg = len(r)
    for i in range(len(s) - lg + 1):
        if s[i:(i+lg)] == r:
            matches.append(i + 1)
    return matches


s = """ATCAGAGTATTCATAGAGTATGAGAGTATAGGAGAGTATGTACAGAGTATCTGAAGA
GTATAGAGTATAGAGTATTAGAGTATTGCGCAAGAGAGTATTGACCAGAGTATTGAGAGTATTA
GCAGAGTATGAGAGTATAGAGTATGAGAGTATAAGAGAGTATAGAGTATCCAAGAGTATAGAGT
ATCAGAGTATAGAGTATAGAGTATGAGAGTATACCACCAGAGTATAGCAGAGTATTTAAAGAGA
GTATGAGAGTATTAGAGTATCAGAGTATGAGAGTATAGAGAGAGTATTGAGAGTATATAGAGTA
TGGCAGAGTATCGAGAGTATGAGAGTATAAGAGTATAGAGTATTTAGAGTATGAGAGTATTCAA
ATACAGAGAGTATCAGAGTATTTTAGAGTATAGAGTATCATTCCAGAGTATTAGAGTATAGAGT
ATTAGTTAGAGTATGACCGAGAGTATAGAGTATAGAGTATGAGAGTATGTTTTGTGAGAGTATG
GGAGAGTATGAAGAGTATTACAAGAGTATCCGATGAGAGTATTAGAGTATTGATAGAGTATCTT
TAAGACAGAGTATGAGAGTATATCAAGAGTATGCACAGAGTATTCAGAGTATAGAGTATAGAGT
ATAGGAAGAGTATCAGAGAGTATCTCTAGAGTATTAGAGTATTAGAGTATGTTGAGAGTATCAG
TCACATAGAGTATAGAGTATTAACATAAGAGTATCTAGAGTATTAGAGTATTAGAGTATAGAGT
ATGGAGAGTATAGAGTATCAGAGTATTGGAAGAGTAT"""

print(get_matches(s, "AGAGTATAG"))
